id,cleaned_report_title,report_category_name,summary,text_content,is_waste,sample_task_id,sample_report_title,sample_report_text,user_id,created,updated,first_found,last_found,count,error_task_time,log_task_time,requeue_task_time,report_category_weight,predicted_task_time,predicted_task_status_error,predicted_task_status_completed,predicted_job_status,plugin
0,--,no category,marked for Admin to categorise,This is assigned manually to mark a error for further investigation. No category errors should be reviewed by an Admin and see if an existing category exists that fits or a new one needs to be created. Only Admins should create new categories to avoid multiple variations of the SAME category being created.,TRUE,,,,,,,,,,,,,,,,,,NULL
1,stalled worker report,stalled worker report,Deadline worker/slave has crashed,The worker has crashed. If this error has occured it is likely the render slave has stalled or is in a stalled state. ,TRUE,,STALLED WORKER REPORT,,,,,,,,,,,,,,,,Redshift
2,error error spacebox unable to create directory file exists at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unable to create directory,Folder could not be created,"The render folder that is trying to be created is unable to be created. This can be a general windows problem as if a process has stalled when trying to create a directory, it can be seen as ""open"" by other processes.   It could also point to permission issues.  Please pass this over to Systems Administrators",TRUE,,"Error: FailRenderException : >>> [14:18.51] ERROR: MainWrite: Unable to create directory '//bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ02/0010_NJ02/exr/', File exists    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I07plugins6054b2d77bf4173f68a7b1b0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I07plugins6054b2d77bf4173f68a7b1b0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I07plugins6054b2d77bf4173f68a7b1b0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I07plugins6054b2d77bf4173f68a7b1b0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
3,error monitored managed process nuke has exited or been terminated at name at name at name file line in rendertasks file line in writepython file line in at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,nuke has exited or been terminated,Nuke has crashed due to computation error,"The application ""NUKE"" has crashed due to issues revolving around the .nk script. This can be multiple issues however it is likely that the script itself is very heavy in regards to computation.  Please look into the scene and optimize the scene. ",TRUE,6026ad2bb0c0ab46f83fa340_72,"Error: ManagedProcessAbort : Monitored managed process Nuke has exited or been terminated.    at Deadline.Plugins.DeadlinePlugin.MonitoredManagedProcessExit(String name)    at FranticX.Processes.MonitoredManagedProcesses.VerifyMonitoredManagedProcess(String name)    at Deadline.Plugins.DeadlinePlugin.VerifyMonitoredManagedProcess(String name) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 45, in WaitForProcess     self.VerifyMonitoredManagedProcess( self.ProcessName )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)","""======================================================= Error ======================================================= The Plugin's Sandbox process is alive but unresponsive. Aborting Render...  ======================================================= Type ======================================================= RenderPluginException  ======================================================= Stack Trace =======================================================    at Deadline.Plugins.SandboxedPlugin.d(DeadlineMessage bcw, CancellationToken bcx)    at Deadline.Plugins.SandboxedPlugin.RenderTask(Task task, CancellationToken cancellationToken)    at Deadline.Slaves.SlaveRenderThread.c(TaskLogWriter aew, CancellationToken aex)  ======================================================= Log ======================================================= 2021-02-12 16:33:26:  0: Render Thread - Render State transition from = 'ReceivedTask' to = 'Other' 2021-02-12 16:33:26:  0: Plugin will be reloaded because a new job has been loaded. 2021-02-12 16:33:26:  0: Loading Job's Plugin timeout is Disabled 2021-02-12 16:33:28:  0: Loaded plugin Nuke 2021-02-12 16:33:28:  0: Executing plugin command of type 'Sync Files for Job' 2021-02-12 16:33:28:  0: All job files are already synchronized 2021-02-12 16:33:28:  0: Synchronizing Plugin Nuke from deadlineDeadlineRepositorypluginsNuke took: 0 seconds 2021-02-12 16:33:28:  0: Done executing plugin command of type 'Sync Files for Job' 2021-02-12 16:33:28:  0: Executing plugin command of type 'Initialize Plugin' 2021-02-12 16:33:28:  0: INFO: Executing plugin script 'C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I02plugins6026ad2bb0c0ab46f83fa340Nuke.py' 2021-02-12 16:33:28:  0: INFO: About: Nuke Plugin for Deadline 2021-02-12 16:33:28:  0: INFO: Render Job As User disabled, running as current user 'sir.render' 2021-02-12 16:33:28:  0: INFO: The job's environment will be merged with the current environment before rendering 2021-02-12 16:33:28:  0: Done executing plugin command of type 'Initialize Plugin' 2021-02-12 16:33:29:  0: Start Job timeout is disabled. 2021-02-12 16:33:29:  0: Task timeout is 273 seconds (Auto Task Timeout) 2021-02-12 16:33:29:  0: Loaded job: 0660_NJ03_COMP_TK08.nk - MainWrite2 (6026ad2bb0c0ab46f83fa340) 2021-02-12 16:33:29:  0: Executing plugin command of type 'Start Job' 2021-02-12 16:33:29:  0: DEBUG: S3BackedCache Client is not installed. 2021-02-12 16:33:29:  0: INFO: Executing global asset transfer preload script 'C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I02plugins6026ad2bb0c0ab46f83fa340GlobalAssetTransferPreLoad.py' 2021-02-12 16:33:29:  0: INFO: Looking for legacy (pre-10.0.26) AWS Portal File Transfer... 2021-02-12 16:33:29:  0: INFO: Looking for legacy (pre-10.0.26) File Transfer controller in C:/Program Files/Thinkbox/S3BackedCache/bin/task.py... 2021-02-12 16:33:29:  0: INFO: Could not find legacy (pre-10.0.26) AWS Portal File Transfer. 2021-02-12 16:33:29:  0: INFO: Legacy (pre-10.0.26) AWS Portal File Transfer is not installed on the system. 2021-02-12 16:33:29:  0: INFO: Prepping OFX cache 2021-02-12 16:33:29:  0: INFO: Checking Nuke temp path: C:Userssir.renderAppDataLocalTempnuke 2021-02-12 16:33:29:  0: INFO: Path already exists 2021-02-12 16:33:29:  0: INFO: OFX cache prepped 2021-02-12 16:33:29:  0: INFO: Starting monitored managed process Nuke 2021-02-12 16:33:29:  0: INFO: Enable Path Mapping: True 2021-02-12 16:33:29:  0: INFO: Stdout Redirection Enabled: True 2021-02-12 16:33:29:  0: INFO: Stdout Handling Enabled: True 2021-02-12 16:33:29:  0: INFO: Popup Handling Enabled: True 2021-02-12 16:33:29:  0: INFO: QT Popup Handling Enabled: False 2021-02-12 16:33:29:  0: INFO: WindowsForms10.Window.8.app.* Popup Handling Enabled: False 2021-02-12 16:33:29:  0: INFO: Using Process Tree: True 2021-02-12 16:33:29:  0: INFO: Hiding DOS Window: True 2021-02-12 16:33:29:  0: INFO: Creating New Console: False 2021-02-12 16:33:29:  0: INFO: Running as user: sir.render 2021-02-12 16:33:29:  0: INFO: Executable: ""C:Program FilesNuke12.0v3Nuke12.0.exe"" 2021-02-12 16:33:29:  0: INFO: Setting Process Environment Variable EDDY_DEVICE_LIST to  2021-02-12 16:33:29:  0: INFO: Argument: -V 2 -t ""C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I02jobsData6026ad2bb0c0ab46f83fa340thread0_templDhkF00660_NJ03_COMP_TK08.nk"" 2021-02-12 16:33:29:  0: INFO: Full Command: ""C:Program FilesNuke12.0v3Nuke12.0.exe"" -V 2 -t ""C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I02jobsData6026ad2bb0c0ab46f83fa340thread0_templDhkF00660_NJ03_COMP_TK08.nk"" 2021-02-12 16:33:29:  0: INFO: Startup Directory: ""C:Program FilesNuke12.0v3"" 2021-02-12 16:33:29:  0: INFO: Process Priority: BelowNormal 2021-02-12 16:33:29:  0: INFO: Process Affinity: default 2021-02-12 16:33:29:  0: INFO: Process is now running 2021-02-12 16:33:29:  0: Done executing plugin command of type 'Start Job' 2021-02-12 16:33:29:  0: Plugin rendering frame(s): 72 2021-02-12 16:33:29:  0: Render Thread - Render State transition from = 'Other' to = 'Rendering' 2021-02-12 16:33:29:  0: Executing plugin command of type 'Render Task' 2021-02-12 16:33:29:  0: INFO: Rendering write node MainWrite2 2021-02-12 16:33:29:  0: STDOUT: Nuke 12.0v3, 64 bit, built Nov 12 2019. 2021-02-12 16:33:29:  0: STDOUT: Copyright (c) 2019 The Foundry Visionmongers Ltd.  All Rights Reserved. 2021-02-12 16:33:29:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/_pathsetup.py 2021-02-12 16:33:29:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/init.tcl 2021-02-12 16:33:29:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/init.py 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/setenv.tcl 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/formats.tcl 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/caravr/init.py 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Users/sir.render/.nuke/init.py 2021-02-12 16:33:30:  0: STDOUT: Loading //bstorage/PIPELINE/repos/nuke-scripts/init.py 2021-02-12 16:33:30:  0: STDOUT: Loading //bstorage/PIPELINE/repos/nuke-scripts/Repository/Gizmos/init.py 2021-02-12 16:33:30:  0: STDOUT: ('CUSTOM_GIZMO_LOCATION', '\bstoragePIPELINEreposnuke-scriptsRepositoryGizmos') 2021-02-12 16:33:30:  0: STDOUT: ('searchPaths', ['\bstoragePIPELINEreposnuke-scriptsRepositoryGizmos']) 2021-02-12 16:33:30:  0: STDOUT: Loading //bstorage/PIPELINE/repos/nuke-scripts/Tools/CryptomatteUtilities/init.py 2021-02-12 16:33:30:  0: STDOUT: Loading //bstorage/PIPELINE/repos/nuke-scripts/Deadline/init.py 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/getenv.tcl 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/OCIOColorSpace.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/exrReader.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/LayerContactSheet.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Merge2.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/dpxReader.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/IBKColourV3.gizmo 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Grade.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Clamp.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/IBK.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Invert.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Erode.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Copy.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Premult.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/FilterErode.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Merge.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/IBKGizmoV3.gizmo 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Transform.dll 2021-02-12 16:33:30:  0: STDOUT: Loading //bstorage/PIPELINE/repos/nuke-scripts/Tools/CryptomatteUtilities/Cryptomatte.gizmo 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Remove.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/pngReader.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Tile.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/tgaReader.tcl 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/targaReader.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Colorspace.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Add.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Multiply.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Keymix.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Constant.dll 2021-02-12 16:33:30:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmosFilter/fizzle.gizmo 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/CheckerBoard2.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Reformat.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Gamma.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/CameraShake.gizmo 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/VectorBlur.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/TimeBlur.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Position.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Saturation.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/EXPTool.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/IDistort.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/PerspDistort.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/STMap.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/mp4Reader.tcl 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/movReader.dll 2021-02-12 16:33:30:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmosFilter/bm_OpticalGlow.gizmo 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/ColorCorrect.dll 2021-02-12 16:33:30:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Dissolve.dll 2021-02-12 16:33:31:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmosDespill/L_Despill_v05.gizmo 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Log2Lin.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Median.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/CopyBBox.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/ZDefocus2.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/AddChannels.dll 2021-02-12 16:33:31:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmospacksL_Tools/L_CropBBox_v01.gizmo 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Crop.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Defocus.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Keyer.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/ChannelMerge.dll 2021-02-12 16:33:31:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmospacksSB_Tools/sb_lensReflections.gizmo 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Noise.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/GodRays.dll 2021-02-12 16:33:31:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmosNoise/Grain_CB.gizmo 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/ColorLookup.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Sharpen.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/CCorrect.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/ModifyMetaData.dll 2021-02-12 16:33:31:  0: STDOUT: Loading bstoragepipelinereposnuke-scriptsrepositorygizmoshandygizmosFilter/fl_VirtualLens.gizmo 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Radial.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/BlackOutside.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Convolve2.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/BlinkScript.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Ramp.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/HueShift.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/exrWriter.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Camera2.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Scene.tcl 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/MergeGeo.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/ScanlineRender.dll 2021-02-12 16:33:31:  0: STDOUT: Loading C:/Program Files/Nuke12.0v3/plugins/Tracker4.dll 2021-02-12 16:33:32:  0: STDOUT: [16:33:31 GMT Standard Time] Read nuke script: C:/Users/sir.render/AppData/Local/Thinkbox/Deadline10/slave/CONA17-_I02/jobsData/6026ad2bb0c0ab46f83fa340/thread0_templDhkF0/0660_NJ03_COMP_TK08.nk 2021-02-12 16:33:32:  0: STDOUT: >>> [16:33.32] Warning: root: Got request for zero or negative-sized box 2021-02-12 22:37:00:  0: An exception occurred: The Plugin's Sandbox process is alive but unresponsive. Aborting Render... (Deadline.Plugins.RenderPluginException)  ======================================================= Details ======================================================= Date: 02/12/2021 22:36:11 Frames: 72 Elapsed Time: 00:06:06:45 Job Submit Date: 02/12/2021 16:26:37 Job User: chris.mckenna Average RAM Usage: 62193827840 (91%) Peak RAM Usage: 68036386816 (100%) Average CPU Usage: 31% Peak CPU Usage: 91% Used CPU Clocks (x10^6 cycles): 392183808 Total CPU Clocks (x10^6 cycles): 1265109079  ======================================================= Worker Information ======================================================= Worker Name: CONA17-_I02 Version: v10.1.9.2 Release (3d6a64d94) Operating System: Windows 10 Pro Running As Service: No Machine User: sir.render IP Address: 192.168.1.68 MAC Address: 0C:9D:92:16:49:8A CPU Architecture: x64 CPUs: 16 CPU Usage: 12% Memory Usage: 63.4 GB / 63.7 GB (99%) Free Disk Space: 761.456 GB (26.668 GB on C:, 734.788 GB on D:) Video Card: NVIDIA GeForce RTX 2070"" ",,,,,,,,,,,,,,,Nuke
4,the worker did not complete the task before the auto task timeout limit of d h m s the auto task timeout settings can be configured in the repository options or this feature can be disabled for this job by rightclicking on it in the monitor and selecting modify properties,the worker did not complete the task before the auto task timeout limit,Frame took too long to render,"Deadline has an ""auto-task timeout"" If it detects a task/frame that takes longer than the average task/frame time, it will fail.  If this has happened in error please pass this onto the Systems Administrators",TRUE,,"The Worker did not complete the task before the Auto Task Timeout limit of 00d 00h 31m 58s. The Auto Task Timeout settings can be configured in the Repository Options, or this feature can be disabled for this job by right-clicking on it in the Monitor and selecting Modify Properties....",,,,,,,,,,,,,,,,Redshift
5,access to the path is denied,access to the path is denied,Permission and security issue,This is a security issue where the user or slave is unable to access the network path.   Please pass this on to the Systems Administrator,TRUE,,Access to the path 'C:Usersdylan.cooperAppDataLocalThinkboxDeadline10slavePILA04-_I02plugins6059b6143e1f1a4760b5d8f9GlobalAssetTransferPreLoad.py' is denied.,,,,,,,,,,,,,,,,Redshift
6,error error zdefocus unknown command this is most likely from corrupt nk file or from missing or unlicensed plugin cant render from that node at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unknown command this is most likely from corrupt nk file or from missing or unlicensed plugin,User has a disapproved effect or plugin in script,"Plugins are effects and that ""plugged in"" to nuke EG. Mocha pro.  These plugins need to exist on all machines in order to render. This is the main reason why we have a repository of plugins which all users share. If this error occurs a user has installed a plugin manually that has not been added to the store.   Please either pass the plugin on to your HOD for approval and integration or delete from your machine/script",TRUE,,"Error: FailRenderException : [17:20.44] ERROR: ZDefocus1: 'ZDefocus2': unknown command. This is most likely from a corrupt .nk file, or from a missing or unlicensed plug-in. Can't render from that Node.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins6058d04284cc0f226459d7c0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
7,the plugins sandbox process is alive but unresponsive aborting render,the plugins sandbox process is alive but unresponsive aborting render,"Deadline's ""sandbox"" has timed out","Deadline has a ""sandbox"" that opens up per slave. This is where the plugin or application gets processed and logged by deadline.   This sandbox is it's own application and is subject to crashing  In this case - the sandbox has not crashed but is not responding to requests and has timed out or aborted.",TRUE,,The Plugin's Sandbox process is alive but unresponsive. Aborting Render...,,,,,,,,,,,,,,,,Nuke
8,timed out while waiting for data,timed out while waiting for data,Unresponsive machine/transfer/data before time out limit was reached,"Each script or process has a time out. If that timeout is reached during execution then an error or exception is ""thrown""   In this case, the data was not loaded in before the timeout was reached causing the error. This can be benign but if seen reguarly please pass this on to the System Administrators.",TRUE,6026ad2bb0c0ab46f83fa340_40,Timed out while waiting for data,,,,,,,,,,,,,,,,Nuke
9,error error defocus bad allocation at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,bad allocation,Failed to load into memory,This is a memory issue. The assets were unable to load into RAM.   If this is happening to your shot please look into your script for optimization,TRUE,,"Error: FailRenderException : [10:43.20] ERROR: Defocus2: bad allocation    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins60474cca9768065370431016Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins60474cca9768065370431016Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins60474cca9768065370431016Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins60474cca9768065370431016Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
10,sandbox process exited unexpectedly while waiting for response from plugin,sandbox process exited unexpectedly while waiting for response from plugin,"Deadline's ""sandbox"" has stalled or crashed","Deadline has a ""sandbox"" that opens up per slave. This is where the plugin or application gets processed and logged by deadline.   This sandbox is it's own application and is subject to crashing  In this case - Deadline's Sandbox has crashed waiting for the plugin to communicate",TRUE,,Sandbox process exited unexpectedly while waiting for response from Plugin.,,,,,,,,,,,,,,,,Redshift
11,error error read footagecloud tanksspace mov reader failed to decode frame invalid data found when processing input at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,mov64Reader failed to decode frame Invalid data found when processing input,Quicktime Codec issue,"This is due to either an uninstalled or corrupt quicktime codecs, please reinstall or install quicktime in order to fix.",TRUE,,"Error: FailRenderException : >>> [10:35.02] ERROR: Read21: //bstorage/projects/NJ/04_PRODUCTION/NJ00_REUSE_MATERIALS/STOCK FOOTAGE/CLOUD TANKS/SPACE KIT/1_Atmospheres/Atmos_3.mp4: mov64Reader failed to decode frame: Invalid data found when processing input    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60489fda4494f83b40dc1e9fNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60489fda4494f83b40dc1e9fNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60489fda4494f83b40dc1e9fNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60489fda4494f83b40dc1e9fNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
12,error deadline was unable to find nuke on the machine comp it tried and failed to find the render executable at these configured checks each of the above paths and will attempt to run only the first program or script that is present on the file system we attempt to provide the typical defaults for you when local render nodes you will need to ensure the particular software is installed and ensure list of globally configured locations is accurate for your configure custom location in the monitor while in super user mode select tools configure plugins nuke then provide the path to the exectuable you would like deadline to run for this plugin if this is thinkbox provided ami for aws portal it may be that the ami in use does not support this particular application please ensure the image has the correct software and version available at message at key string prettyname file line in return exekey nuke selfversion at args at version cultureneutral at waitforexit at string at waitforexit at name managedprocess at name managedprocess string username string domain string password boolean usesu boolean at name managedprocess file line in startjob selfprocess at args at outmessage abortlevel abortlevel at outmessage abortlevel,deadline was unable to find nuke 11.2 on the machine,Wrong version of nuke used.,"During production we use approved versions, so that we do not introudce any extra bugs during time critical time.  If you are getting this error message then the artist needs to check the version they are using.   If you do not have the correct version of the application installed please talk to your Systems Administrator",TRUE,,"Error: ManagedProcessAbort : Error: FailRenderException : Deadline was unable to find Nuke 11.2 on the machine NUKENODE03.  It tried and failed to find the render executable at these configured locations: C:Program FilesNuke11.2v1Nuke11.2.exe /usr/local/Nuke11.2v1/Nuke11.2 /Applications/Nuke11.2v1/Nuke11.2v1.app/Contents/MacOS/Nuke11.2v1  Deadline checks each of the above paths and will attempt to run only the first program or script that is present on the file system. We attempt to provide the typical defaults for you when possible.  For local render nodes, you will need to ensure the particular software is installed and ensure list of globally configured locations is accurate for your installation. To configure a custom location, in the Monitor while in Super User mode select Tools -> Configure Plugins -> Nuke, then provide the path to the exectuable you would like Deadline to run for this plugin.  If this is a Thinkbox provided AMI for AWS Portal, it may be that the AMI in use does not support this particular application. Please ensure the image has the correct software and version available.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message)    at Deadline.Plugins.DeadlinePlugin.GetRenderExecutable(String key, String prettyName) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I02plugins60216d696bb4930df41e00b9Nuke.py, line 418, in RenderExecutable     return self.deadlinePlugin.GetRenderExecutable( exeKey, Nuke %s % self.Version )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0`1[[System_String, System_Private_CoreLib, Version=4_0_0_0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]Dispatcher.Invoke()    at FranticX.Processes.ManagedProcess.RenderExecutable()    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at FranticX.Processes.ManagedProcess.GenerateManagedProcessAbortException(Exception e, String operationName)    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at FranticX.Processes.MonitoredManagedProcesses.StartMonitoredManagedProcess(String name, ManagedProcess managedProcess)    at Deadline.Plugins.DeadlinePlugin.StartMonitoredManagedProcessAsUser(String name, ManagedProcess managedProcess, String userName, String domain, String password, Boolean useSu, Boolean preserveEnvironment, Boolean setHomeVariable)    at Deadline.Plugins.DeadlinePlugin.StartMonitoredManagedProcess(String name, ManagedProcess managedProcess) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I02plugins60216d696bb4930df41e00b9Nuke.py, line 209, in StartJob     self.StartMonitoredManagedProcess( self.ProcessName, self.Process )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.StartJob()    at Deadline.Plugins.DeadlinePlugin.DoStartJob()    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
13,error fatal error out of memory trying to allocate internal tcmalloc data bytes objectsize at message file line in rendertasks file line in writepython file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,out of memory trying to allocate internal tcmalloc data bytes,Out of RAM/Memory,"This is a RAM issue.   Different to allocation, this error identifies the machine has run out of usable RAM  If you are experiencing this error please look into optimizing your scene",TRUE,,"Error: FailRenderException : c:cygdrivecworkspacethirdpartygperftools2.0srcgperftoolssrcpage_heap_allocator.h:73] FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size) 131072 1432     at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I06plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I06plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 37, in WritePython     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I06plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
14,error attributeerror nukeplugin object has no attribute file line in return exekey nuke selfversion at outmessage abortlevel,<> object has no attribute <>,"Nuke node or object does not have the attribute ""X"" - in this case PythonPanel ",Nuke nodes/objects all have an attribute attatched to it.   If you are experience this error please look through your script for any unapproved nodes/objects you have introduced to your script,TRUE,,"Error: Error: AttributeError : 'NukePlugin' object has no attribute 'GetRenderExecutable' (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I04plugins601d781d34ff812c6c9ba5b7Nuke.py, line 418, in RenderExecutable     return self.deadlinePlugin.GetRenderExecutable( exeKey, Nuke %s % self.Version )     at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
15,error memory malloc failed and cannot free anything throwing stdbadalloc this will probably crash error read bad allocation at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,bad allocation memory malloc failed and cannot free anything throwing std,RAM/Memory cannot be released,This is a RAM issue.  This error shows that the slaves memory is unable to be freed as another job is currently still loaded in.   If you are getting this error it is possible that your shot is unoptimized. Please look into your scene for any way to optimize the assets you are loading in,TRUE,,"Error: FailRenderException : Memory: malloc failed and cannot free anything, throwing std::bad_alloc. This will probably crash![10:02.49] ERROR: Read21: bad allocation    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins606c23504c81c365686bb417Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins606c23504c81c365686bb417Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins606c23504c81c365686bb417Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins606c23504c81c365686bb417Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
16,error error keylight effect raised an error during render at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,effect raised an error during render,"""X"" Node has recorded an error (This may be clustered incorrectly)",,TRUE,,"Error: FailRenderException : >>> >>> >>> [17:46.28] ERROR: Keylight1: Effect raised an error during render.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I03plugins60410cae6c761b6f54837d37Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I03plugins60410cae6c761b6f54837d37Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I03plugins60410cae6c761b6f54837d37Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I03plugins60410cae6c761b6f54837d37Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
17,error exception of type was thrown at dg boolean dh at nohandling at name at name file line in rendertasks file line in writepython file line in at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,exception of type system out of memory exception was thrown,Data is too large to fit into RAM/memory,This is a RAM issue.  The assets in your scene that are loading into RAM are too large for the capacity of the machine.  Please look into optimizing your scene,TRUE,,"Error: OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.    at FranticX.Processes.ManagedProcess.RegexHandlerCallback.CallFunction()    at FranticX.Processes.ManagedProcess.e(String dg, Boolean dh)    at FranticX.Processes.ManagedProcess.FlushStdout(Boolean noHandling)    at FranticX.Processes.MonitoredManagedProcesses.FlushStdout(String name)    at Deadline.Plugins.DeadlinePlugin.FlushMonitoredManagedProcessStdout(String name) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins6040c4382967fb47f89d7310Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins6040c4382967fb47f89d7310Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins6040c4382967fb47f89d7310Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
18,error error zdefocus exception while running kernel on device at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,exception while running kernel on device,,,FALSE,,"Error: FailRenderException : [17:24.08] ERROR: ZDefocus1: Exception while running kernel on device    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
19,error runtimeerror uncaught exception occured during the execution of the python script at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,runtime error uncaught c++ exception occured during the execution of the python script,Unexpected General Error,This is a generic error that has not been classified in code level.   Please send this on to the Systems Administrator for logging,TRUE,,"Error: FailRenderException : RuntimeError: Uncaught C++ exception occured during the execution of the python script!    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604246424b39232920bf318fNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604246424b39232920bf318fNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604246424b39232920bf318fNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604246424b39232920bf318fNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
20,error global asset transfer preload script function main is not defined in the global asset transfer preload script at outmessage abortlevel,global asset transfer preload script,File transfer protocol has failed ( Need a little more infor on this error ) ,,TRUE,,"Error: Global asset transfer preload script 'C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I04plugins6020112906e8152ebc715ca6GlobalAssetTransferPreLoad.py': Function __main__ is not defined in the global asset transfer preload script: 'C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I04plugins6020112906e8152ebc715ca6GlobalAssetTransferPreLoad.py' (Deadline.Plugins.RenderPluginException)    at Deadline.Plugins.PluginWrapper.d()    at Deadline.Plugins.PluginWrapper.d()    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Redshift
21,event error onjoberror typeerror onjoberror takes exactly arguments given,type error onjoberror() takes exactly <n> arguments <m> given,,,FALSE,,Event Error (OnJobError): TypeError : OnJobError() takes exactly 2 arguments (4 given),,,,,,,,,,,,,,,,Nuke
22,error global asset transfer preload script function main is not defined in the global asset transfer preload script at outmessage abortlevel,global asset transfer preload script,File transfer protocol has failed ( Need a little more infor on this error ) ,,TRUE,,"Error: Global asset transfer preload script 'C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveGPUNODE01-_I03plugins6094f504b7c457350c615e06GlobalAssetTransferPreLoad.py': Exception of type 'System.OutOfMemoryException' was thrown. (System.OutOfMemoryException)    at Deadline.Scripting.DeadlineScriptManager.CallFunction(String moduleName, String functionName, Object[] args)    at Deadline.Plugins.PluginWrapper.d()    at Deadline.Plugins.PluginWrapper.d()    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
23,event error onjoberror fatal sorry too many clients already,event error onjoberror fatal sorry too many clients already,,,FALSE,,"Event Error (OnJobFinished): OperationalError : FATAL:  sorry, too many clients already ",,,,,,,,,,,,,,,,Nuke
24,error failed to create thread out of resources at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,failed to create thread out of resources,,,FALSE,,"Error: FailRenderException : >>> Error: failed to create thread, out of resources.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins6058d04284cc0f226459d7c0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
25,error error edgeextend couldnt find function at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error couldn't find function <>,,,FALSE,,"Error: FailRenderException : [ 9:16.08] ERROR: EdgeExtend1: Couldn't find function of85b615a27ea3a460.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11plugins6059b00a9ae2802108f9335dNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11plugins6059b00a9ae2802108f9335dNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11plugins6059b00a9ae2802108f9335dNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11plugins6059b00a9ae2802108f9335dNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
26,event error onjoberror sandbox process exited unexpectedly while waiting for response from event,sandbox process exited unexpectedly while waiting for response from event,,,FALSE,,Event Error (OnJobError): Sandbox process exited unexpectedly while waiting for response from Event.,,,,,,,,,,,,,,,,Nuke
27,error error read read error no such file or directory at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,read error: no such file or directory,,,FALSE,,"Error: FailRenderException : >>> [14:34.39] ERROR: Read9: //bstorage/projects/NJ/04_PRODUCTION/NJ02_GREEN_EYED_NOVA/09_FOOTAGE/DENOISED DPXs/0290_NJ02/0290_NJ02_B_23.dpx: Read error: No such file or directory    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins605b4dc954b9c11d486e5162Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins605b4dc954b9c11d486e5162Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins605b4dc954b9c11d486e5162Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins605b4dc954b9c11d486e5162Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
28,error error mainwrite exr write failed cannot open image file permission denied at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"exr write failed cannot open image file, permission denied",,,FALSE,,"Error: FailRenderException : >>> [17:17.50] ERROR: MainWrite: EXR: Write failed [Cannot open image file //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ02/0530_NJ02/exr/8017710282815633734.tmp. Permission denied.]    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins6058d04284cc0f226459d7c0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins6058d04284cc0f226459d7c0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins6058d04284cc0f226459d7c0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins6058d04284cc0f226459d7c0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
29,error error read error reading pixel data from image file early end of file read out of requested bytes at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error reading pixel data from image file,,,FALSE,,"Error: FailRenderException : [13:25.47] ERROR: Read16: Error reading pixel data from image file //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/03.LR/NJ02/4180_NJ02/Jefferson_Wide/4180_NJ02_Jefferson_Wide.0054.exr. Early end of file: read 5173 out of 5980 requested bytes.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I07plugins6054a4a4a542fe392cdd4af5Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I07plugins6054a4a4a542fe392cdd4af5Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I07plugins6054a4a4a542fe392cdd4af5Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I07plugins6054a4a4a542fe392cdd4af5Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
30,error runtimeerror spacebox cannot be executed at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,runtimeerror: <> cannot be executed,,,FALSE,,"Error: FailRenderException : RuntimeError: SPACEBOX cannot be executed    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I06plugins605b7928bf4fd2f9d004f58eNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I06plugins605b7928bf4fd2f9d004f58eNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I06plugins605b7928bf4fd2f9d004f58eNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I06plugins605b7928bf4fd2f9d004f58eNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
31,event error onjobrequeued exception no sound found named nj wav in footagewavs,event error onjobsubmitted exception no sound found named <>,,,FALSE,,"Event Error (OnJobRequeued): Exception : [FINALCOMP_addSound] No sound found named '0360_NJ02.wav' in: [., ../../04_FOOTAGE/WAVs, ../../09_FOOTAGE/WAVs]",,,,,,,,,,,,,,,,Nuke
32,error error mainwrite cant rename tmp to final no such file or directory at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"can't rename .tmp to final, no such file or directory",,,FALSE,,"Error: FailRenderException : >>> [10:06.48] ERROR: MainWrite: Can't rename .tmp to final, No such file or directory    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins6058cc0fcada8c0c58e6f6b0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
33,error error compiling kernel at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error compiling kernel ,,,FALSE,,"Error: FailRenderException : [10:04.15] ERROR: fl_VirtualLens1.Chromatik2.Vector_Chromatic.BlinkScript10: Error compiling kernel    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins605b0e7e3e27306084d205d5Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins605b0e7e3e27306084d205d5Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins605b0e7e3e27306084d205d5Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I04plugins605b0e7e3e27306084d205d5Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
34,error error alternatetk cant rename tmp to final file exists at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"can't rename .tmp to final, file exists",,,FALSE,,"Error: FailRenderException : [ 9:45.55] ERROR: ALTERNATE_TK: Can't rename .tmp to final, File exists    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins605472a40063c14aacd746f0Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins605472a40063c14aacd746f0Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins605472a40063c14aacd746f0Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I03plugins605472a40063c14aacd746f0Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
35,error unable to create cache directory file exists at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unable to create cache directory,,,FALSE,,"Error: FailRenderException : ERROR: Unable to create cache directory,  C:/Users/ADMINI~1/AppData/Local/Temp/nukeofxplugincache, File exists.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I02plugins604646516f2d531828c5eaa4Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I02plugins604646516f2d531828c5eaa4Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I02plugins604646516f2d531828c5eaa4Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I02plugins604646516f2d531828c5eaa4Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
36,error error read bad newhandler cannot free anything throwing stdbadalloc this will probably crash at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,bad allocation new_handler cannot free anything,,,FALSE,,"Error: FailRenderException : [16:59.08] ERROR: Read4: bad allocationMemory: new_handler() cannot free anything, throwing std::bad_alloc. This will probably crash!    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins604100df77d7a82a60888f2bNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins604100df77d7a82a60888f2bNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins604100df77d7a82a60888f2bNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins604100df77d7a82a60888f2bNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
37,error error readgeo no such file or directory at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error: no such file or directory,,,FALSE,,"Error: FailRenderException : >>> [17:53.37] ERROR: ReadGeo3: No such file or directory    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I04plugins6046629b994e8e824480ae29Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I04plugins6046629b994e8e824480ae29Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I04plugins6046629b994e8e824480ae29Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I04plugins6046629b994e8e824480ae29Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
38,error error spacebox error writing invalid argument at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error writing invalid argument,,,FALSE,,"Error: FailRenderException : [17:53.56] ERROR: SPACE_BOX: Error writing: Invalid argument    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I05plugins6046629b994e8e824480ae29Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I05plugins6046629b994e8e824480ae29Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I05plugins6046629b994e8e824480ae29Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE04-_I05plugins6046629b994e8e824480ae29Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
39,error ioexception the process cannot access the file because it is being used by another process at filehandle at mode fileshare share fileoptions options at path filemode mode fileaccess access fileshare share int buffersize fileoptions options at path filemode mode fileaccess access fileshare share at path at bne string bnf string bng string bnh string bni ilist bnj boolean bnk datacontroller bnl bnm string bnn os bno at infilename string outfilename string forceseperator string newstrings datacontroller logfunction string regionid boolean at infilename string outfilename string forceseperator string newstrings datacontroller logfunction string regionid at infilename string outfilename string newstrings datacontroller logfunction string regionid at infilename string outfilename string newstrings file line in scenefilename tclescape file line in infilename outfilename newstrings at args at waitforexit at string at waitforexit at name managedprocess at name managedprocess string username string domain string password boolean usesu boolean at name managedprocess file line in startjob selfprocess at args at outmessage abortlevel abortlevel at outmessage abortlevel,the process cannot access the file <> because it is used by another process,,,FALSE,,"Error: ManagedProcessAbort : Error: IOException : The process cannot access the file 'bstorageprojectsNJ04_PRODUCTIONNJ03_NOVA_HAS_TALENT10_COMPOSITING0221_NJ03_COMP0221_NJ03_COMP_TK30.nk' because it is being used by another process.    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)    at System.IO.File.OpenRead(String path)    at Deadline.IO.PathMappingUtils.c(String bne, String bnf, String bng, String[] bnh, String[] bni, IList`1 bnj, Boolean bnk, DataController bnl, GenericDelegate1`1 bnm, String bnn, OS bno)    at Deadline.IO.PathMappingUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String forceSeperator, String[] stringsToReplace, String[] newStrings, DataController dataController, GenericDelegate1`1 logFunction, String regionID, Boolean readFileAsBytes)    at Deadline.IO.PathMappingUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String forceSeperator, String[] stringsToReplace, String[] newStrings, DataController dataController, GenericDelegate1`1 logFunction, String regionID)    at Deadline.IO.PathMappingUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String[] stringsToReplace, String[] newStrings, DataController dataController, GenericDelegate1`1 logFunction, String regionID)    at Deadline.Scripting.RepositoryUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String[] stringsToReplace, String[] newStrings) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins60460fadc5e8e23df01cab20Nuke.py, line 404, in PreRenderTasks     self.pathMappingWithFilePermissionFix( sceneFilename, self.TempSceneFilename, ([,, _TCL_ESCAPE_), (_TCL_ESCAPE_, /, [) )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins60460fadc5e8e23df01cab20Nuke.py, line 326, in pathMappingWithFilePermissionFix     RepositoryUtils.CheckPathMappingInFileAndReplace( inFileName, outFileName, stringsToReplace, newStrings )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at FranticX.Processes.ManagedProcess.PreRenderTasks()    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at FranticX.Processes.ManagedProcess.GenerateManagedProcessAbortException(Exception e, String operationName)    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at FranticX.Processes.MonitoredManagedProcesses.StartMonitoredManagedProcess(String name, ManagedProcess managedProcess)    at Deadline.Plugins.DeadlinePlugin.StartMonitoredManagedProcessAsUser(String name, ManagedProcess managedProcess, String userName, String domain, String password, Boolean useSu, Boolean preserveEnvironment, Boolean setHomeVariable)    at Deadline.Plugins.DeadlinePlugin.StartMonitoredManagedProcess(String name, ManagedProcess managedProcess) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I03plugins60460fadc5e8e23df01cab20Nuke.py, line 209, in StartJob     self.StartMonitoredManagedProcess( self.ProcessName, self.Process )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.StartJob()    at Deadline.Plugins.DeadlinePlugin.DoStartJob()    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
40,error error read file is empty at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error <.exr> file is empty,,,FALSE,,"Error: FailRenderException : >>> [15:55.51] ERROR: Read1: //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/03.LR/NJ00/0100_NJ00/Hologram_03/0100_NJ00_Hologram_03.0025.exr: file is empty    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I06plugins60464549b7433f3c902f26e1Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I06plugins60464549b7433f3c902f26e1Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I06plugins60464549b7433f3c902f26e1Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I06plugins60464549b7433f3c902f26e1Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
41,error runtimeerror nothing is named mainwrite at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,nothing is named <>,,,FALSE,,"Error: FailRenderException : RuntimeError: Nothing is named MainWrite    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60460fadc5e8e23df01cab20Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60460fadc5e8e23df01cab20Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60460fadc5e8e23df01cab20Nuke.py, line 42, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18plugins60460fadc5e8e23df01cab20Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
42,error error spacebox has no valid channels nothing to write at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,<>  has no valid channels - nothing to write.,,,FALSE,,"Error: FailRenderException : >>> [15:32.58] ERROR: space_box: //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ03/2590_NJ03/take_11/spacerender_tk11.0060.tga: has no valid channels - nothing to write.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins603e5a8984a3e95874aacaf9Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins603e5a8984a3e95874aacaf9Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins603e5a8984a3e95874aacaf9Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I05plugins603e5a8984a3e95874aacaf9Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
43,error error merge nonexistent channel used for mask at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,non-existent channel used for mask,,,FALSE,,"Error: FailRenderException : >>> [12:59.42] ERROR: Merge9: Non-existent channel used for mask    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I08plugins60379f366c37f8419094a3a2Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I08plugins60379f366c37f8419094a3a2Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I08plugins60379f366c37f8419094a3a2Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA11-_I08plugins60379f366c37f8419094a3a2Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
44,error error read footagecloud tanksspace mov reader reader failed to read frame error number occurred at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,mov64reader reader failed to read frame: error number 12 occurred,,,FALSE,,"Error: FailRenderException : >>> >>> >>> [10:15.34] ERROR: Read23: //bstorage/projects/NJ/04_PRODUCTION/NJ00_REUSE_MATERIALS/STOCK FOOTAGE/CLOUD TANKS/SPACE KIT/1_Atmospheres/Atmos_6.mp4: mov64Reader Reader failed to read frame: Error number -12 occurred    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I02plugins603e0fc3fedd901e786aee4dNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I02plugins603e0fc3fedd901e786aee4dNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I02plugins603e0fc3fedd901e786aee4dNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I02plugins603e0fc3fedd901e786aee4dNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
45,error error running kernel at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,exception running kernel,,,FALSE,,"Error: FailRenderException : [10:19.04] ERROR: fl_VirtualLens2.Chromatik2.RadialVectorGenerator1.BlinkScript8: Error running kernel    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I03plugins603e0fc3fedd901e786aee4dNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I03plugins603e0fc3fedd901e786aee4dNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I03plugins603e0fc3fedd901e786aee4dNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I03plugins603e0fc3fedd901e786aee4dNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
46,error error read cprogram the paging file is too small for this operation to complete at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,the paging file is too small for this operation to complete,,,FALSE,,"Error: FailRenderException : [11:40.28] ERROR: Read3: C:/Program Files/Nuke12.0v3/plugins/movReader.dll: The paging file is too small for this operation to complete.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03plugins603cd1d24f7f6121248937f1Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03plugins603cd1d24f7f6121248937f1Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03plugins603cd1d24f7f6121248937f1Nuke.py, line 42, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03plugins603cd1d24f7f6121248937f1Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
47,error error read footagecloud tanksspace unable to find video stream at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unable to find video stream,,,FALSE,,"Error: FailRenderException : >>> [ 9:57.08] ERROR: Read7: //bstorage/projects/NJ/04_PRODUCTION/NJ00_REUSE_MATERIALS/STOCK FOOTAGE/CLOUD TANKS/SPACE KIT/1_Atmospheres/Atmos_6.mp4: unable to find video stream    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins603cd1d24f7f6121248937f1Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins603cd1d24f7f6121248937f1Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins603cd1d24f7f6121248937f1Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I02plugins603cd1d24f7f6121248937f1Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
48,error unable to create disk cache at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unable to create disk cache at <>,,,FALSE,,"Error: FailRenderException : ERROR: Unable to create disk cache at C:/Users/SIR~1.REN/AppData/Local/Temp/nuke.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins60379f8153bb4e39f09eee42Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins60379f8153bb4e39f09eee42Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins60379f8153bb4e39f09eee42Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01-_I04plugins60379f8153bb4e39f09eee42Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
49,error error particlewind creation error while trying to create particlemove cprogram the paging file is too small for this operation to complete at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,creation error while trying to create <>,,,FALSE,,"Error: FailRenderException : >>> [16:13.02] ERROR: ParticleWind1: Creation error while trying to create (ParticleMove): C:/Program Files/Nuke12.0v3/plugins/ParticleMove.dll: The paging file is too small for this operation to complete.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I03plugins60353bcebff33e357051a8afNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I03plugins60353bcebff33e357051a8afNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I03plugins60353bcebff33e357051a8afNuke.py, line 45, in WaitForProcess     self.VerifyMonitoredManagedProcess( self.ProcessName )   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I03plugins60353bcebff33e357051a8afNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
50,error importerror could not import module pyside qtgui at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,import error: couldn't import module <>,,,FALSE,,"Error: FailRenderException : ImportError: could not import module 'PySide2.QtGui'    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I05plugins602678ee67a4b93a1498b0beNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I05plugins602678ee67a4b93a1498b0beNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I05plugins602678ee67a4b93a1498b0beNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA18-_I05plugins602678ee67a4b93a1498b0beNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
51,event error onjobfinished could not connect to server connection timed out the server running on host jamalytics and connections on port,operational error: could not connect to server,,,FALSE,,"Event Error (OnJobFinished): OperationalError : could not connect to server: Connection timed out (0x0000274C/10060) 	Is the server running on host jamalytics (192.168.1.120) and accepting 	TCP/IP connections on port 5432? ",,,,,,,,,,,,,,,,Nuke
52,unable to load dll python or one of its dependencies the paging file is too small for this operation to complete x af,unable to load dll <> or one of its dependencies. the paging file is too small for this operation to complete,,,FALSE,,Unable to load DLL 'python27' or one of its dependencies: The paging file is too small for this operation to complete. (0x800705AF),,,,,,,,,,,,,,,,Nuke
53,error error cannot read from file does not match input at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,cannot read from file; file does not match input,,,FALSE,,"Error: FailRenderException : >>> [16:04.30] ERROR: SPACEBOX1_precomp.SPACEBOX1_precomp_write: //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ03/0900_NJ03/precomps/SPACEBOX1_precomp/SPACEBOX1_precomp_0900_NJ03.000000.exr: Cannot read from file; file does not match input.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins60215df61e1fc15dd0519c36Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins60215df61e1fc15dd0519c36Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins60215df61e1fc15dd0519c36Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins60215df61e1fc15dd0519c36Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
54,error importerror dll load failed the paging file is too small for this operation to complete at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,import error: dll load failed. the paging file is too small for this operation to complete,,,FALSE,,"Error: FailRenderException : ImportError: DLL load failed: The paging file is too small for this operation to complete.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP16-_I04plugins6022a650edaee83d747d0c0dNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP16-_I04plugins6022a650edaee83d747d0c0dNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP16-_I04plugins6022a650edaee83d747d0c0dNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP16-_I04plugins6022a650edaee83d747d0c0dNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
55,error error mainwrite exr write failed to write pixel data to image file invalid argument at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,write failed to write pixel data to image file,,,FALSE,,"Error: FailRenderException : [14:24.34] ERROR: MainWrite: EXR: Write failed [Failed to write pixel data to image file //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ03/2280_NJ03/exr/-6682406295305353986.tmp. Invalid argument.]    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012plugins602297dc4936941db8591d0bNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012plugins602297dc4936941db8591d0bNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012plugins602297dc4936941db8591d0bNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012plugins602297dc4936941db8591d0bNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
56,error error read and motion graphicsnjuht screen motion graphicsuht screen mov mov reader reader failed to read frame error number occurred at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,mov64reader reader failed to read frame: error number 22 occurred,,,FALSE,,"Error: FailRenderException : >>> [21:11.41] ERROR: Read2: //bstorage/projects/NJ/04_PRODUCTION/NJ00_ASSETS/LOGO AND MOTION GRAPHICS/NJ_UHT SCREEN MOTION GRAPHICS/UHT SCREEN_02.mov: mov64Reader Reader failed to read frame: Error number -22 occurred    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I07plugins602179dccf3c443c1c71f17cNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I07plugins602179dccf3c443c1c71f17cNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I07plugins602179dccf3c443c1c71f17cNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA17-_I07plugins602179dccf3c443c1c71f17cNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
57,event error onjobsubmitted importerror no module named,import error: no module named <>,,,FALSE,,Event Error (OnJobSubmitted): ImportError : No module named FINALCOMP_addSound,,,,,,,,,,,,,,,,Nuke
58,error error read libpng error at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,libpng error,,,FALSE,,"Error: FailRenderException : [13:40.57] ERROR: Read11: libpng error    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I07plugins602132d0e58be939402c68cfNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I07plugins602132d0e58be939402c68cfNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I07plugins602132d0e58be939402c68cfNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE03-_I07plugins602132d0e58be939402c68cfNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
59,error error key cant rename tmp to final invalid argument at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"can't rename .tmp to final, invalid argument",,,FALSE,,"Error: FailRenderException : [18:51.09] ERROR: KEY: Can't rename .tmp to final, Invalid argument    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I08plugins604a350ab33a552d98395196Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I08plugins604a350ab33a552d98395196Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I08plugins604a350ab33a552d98395196Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06-_I08plugins604a350ab33a552d98395196Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
60,error error spacebox cant rename tmp to final permission denied at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"can't rename .tmp to final, permission denied",,,FALSE,,"Error: FailRenderException : >>> [15:44.03] ERROR: SPACEBOX: Can't rename .tmp to final, Permission denied    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins604a3504d541693584306698Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins604a3504d541693584306698Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins604a3504d541693584306698Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveRYZEN01plugins604a3504d541693584306698Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
61,error error mainwrite cant write invalid argument at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"can't write, invalid argument",,,FALSE,,"Error: FailRenderException : >>> [ 9:37.06] ERROR: MainWrite1: Can't write, Invalid argument    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60507af9d2e89c3a1c71cafbNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60507af9d2e89c3a1c71cafbNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60507af9d2e89c3a1c71cafbNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60507af9d2e89c3a1c71cafbNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
62,error error mainwrite exrwriter no channels selected or available for write at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,no channels selected (or available) to write,,,FALSE,,"Error: FailRenderException : >>> [16:52.54] ERROR: MainWrite: exrWriter: No channels selected (or available) for write    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604f90dfef693619704adad5Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604f90dfef693619704adad5Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604f90dfef693619704adad5Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I05plugins604f90dfef693619704adad5Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
63,error error key no plugin named writer found at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,no plugin named <>,,,FALSE,,"Error: FailRenderException : [12:32.15] ERROR: KEY: //bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ02/9999_NJ02/KEY_TUTORIAL/9999_NJ02_COMP_KEY.0010: no plugin named 0010Writer found    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins604b556f3daf9c1ce06521e5Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins604b556f3daf9c1ce06521e5Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins604b556f3daf9c1ce06521e5Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins604b556f3daf9c1ce06521e5Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
64,object reference not set to an instance of an object,object reference not set to an instance of an object,,,FALSE,,Object reference not set to an instance of an object.,,,,,,,,,,,,,,,,Nuke
65,error runtimeerror you must specify proxy file name to write to at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,you must specify a proxy file name to write to,,,FALSE,,"Error: FailRenderException : RuntimeError: You must specify a proxy file name to write to.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I04plugins6087d27c316c244568abd07eNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I04plugins6087d27c316c244568abd07eNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I04plugins6087d27c316c244568abd07eNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE02-_I04plugins6087d27c316c244568abd07eNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
66,error error read data decompression zlib failed at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,data compression <> failed,,,FALSE,,"Error: FailRenderException : >>> [15:53.27] ERROR: Read2: Data decompression (zlib) failed.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA07-_I04plugins607d9929670fcd35d04c02a3Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA07-_I04plugins607d9929670fcd35d04c02a3Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA07-_I04plugins607d9929670fcd35d04c02a3Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA07-_I04plugins607d9929670fcd35d04c02a3Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
67,error error particlecache particlecache is outofdate at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,<> is out-of-date,,,FALSE,,"Error: FailRenderException : >>> [12:39.31] ERROR: ParticleCache1: ParticleCache is out-of-date    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE07-_I05plugins60893f10914439333007349eNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE07-_I05plugins60893f10914439333007349eNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE07-_I05plugins60893f10914439333007349eNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE07-_I05plugins60893f10914439333007349eNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
68,sandbox process is not available may be disposed already,sandbox process is not available may be disposed already,,,FALSE,,"Sandbox Process is not available, may be disposed already.",,,,,,,,,,,,,,,,Nuke
69,error error particlecache particlecache data not found at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,<> data not found,,,FALSE,,"Error: FailRenderException : >>> [11:31.21] ERROR: ParticleCache1: ParticleCache data not found    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60912286754a751894fa8cbbNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60912286754a751894fa8cbbNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60912286754a751894fa8cbbNuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I02plugins60912286754a751894fa8cbbNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
70,error error bad value for viewerprocess film srgb at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,bad value for <> film (sRGB),,,FALSE,,"Error: FailRenderException : [14:05.06] ERROR: Bad value for viewerProcess : Film (sRGB)    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins609297f679ab7403a881514aNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins609297f679ab7403a881514aNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins609297f679ab7403a881514aNuke.py, line 42, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCONA21-_I03plugins609297f679ab7403a881514aNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
71,error error read and motion graphicsnj screen mov reader reader failed to read frame end of file at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,mov64reader reader failed to read frame: end of file,,,FALSE,,"Error: FailRenderException : >>> [12:59.48] ERROR: Read6: //bstorage/projects/NJ/04_PRODUCTION/NJ00_ASSETS/LOGO AND MOTION GRAPHICS/NJ _ SCREEN UI_001/NJ05_UI_SC770.mp4: mov64Reader Reader failed to read frame: End of file    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins6093d50016a8de1c5ca8aba7Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins6093d50016a8de1c5ca8aba7Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins6093d50016a8de1c5ca8aba7Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Usersjon.tennentAppDataLocalThinkboxDeadline10slaveCONA03-_I05plugins6093d50016a8de1c5ca8aba7Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
72,error could not find file at filehandle at mode fileshare share fileoptions options at path filemode mode fileaccess access fileshare share int buffersize fileoptions options at path filemode mode fileaccess access fileshare share at path at bne string bnf string bng string bnh string bni ilist bnj boolean bnk datacontroller bnl bnm string bnn os bno at infilename string outfilename string forceseperator string newstrings datacontroller logfunction string regionid boolean at infilename string outfilename string forceseperator string newstrings datacontroller logfunction string regionid at infilename string outfilename string newstrings datacontroller logfunction string regionid at infilename string outfilename string newstrings file line in scenefilename tclescape file line in infilename outfilename newstrings at args at waitforexit at string at waitforexit at name managedprocess at name managedprocess string username string domain string password boolean usesu boolean at name managedprocess file line in startjob selfprocess at args at outmessage abortlevel abortlevel at outmessage abortlevel,could not find file <>,,,FALSE,,"Error: ManagedProcessAbort : Error: FileNotFoundException : Could not find file 'bstorageprojectsNJ04_PRODUCTIONNJ05_TANTRUM_BY_NOVA10_COMPOSITING0940_NJ05_COMPNJ05_0940_0960_1000_1020_1050_1530_1550_15700000_NJ05_COMP_TK01.nk'.    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)    at System.IO.File.OpenRead(String path)    at Deadline.IO.PathMappingUtils.c(String bne, String bnf, String bng, String[] bnh, String[] bni, IList`1 bnj, Boolean bnk, DataController bnl, GenericDelegate1`1 bnm, String bnn, OS bno)    at Deadline.IO.PathMappingUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String forceSeperator, String[] stringsToReplace, String[] newStrings, DataController dataController, GenericDelegate1`1 logFunction, String regionID, Boolean readFileAsBytes)    at Deadline.IO.PathMappingUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String forceSeperator, String[] stringsToReplace, String[] newStrings, DataController dataController, GenericDelegate1`1 logFunction, String regionID)    at Deadline.IO.PathMappingUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String[] stringsToReplace, String[] newStrings, DataController dataController, GenericDelegate1`1 logFunction, String regionID)    at Deadline.Scripting.RepositoryUtils.CheckPathMappingInFileAndReplace(String inFileName, String outFileName, String[] stringsToReplace, String[] newStrings) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE05-_I05plugins6093ee9580628310c00de09fNuke.py, line 404, in PreRenderTasks     self.pathMappingWithFilePermissionFix( sceneFilename, self.TempSceneFilename, ([,, _TCL_ESCAPE_), (_TCL_ESCAPE_, /, [) )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE05-_I05plugins6093ee9580628310c00de09fNuke.py, line 326, in pathMappingWithFilePermissionFix     RepositoryUtils.CheckPathMappingInFileAndReplace( inFileName, outFileName, stringsToReplace, newStrings )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at FranticX.Processes.ManagedProcess.PreRenderTasks()    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at FranticX.Processes.ManagedProcess.GenerateManagedProcessAbortException(Exception e, String operationName)    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at FranticX.Processes.MonitoredManagedProcesses.StartMonitoredManagedProcess(String name, ManagedProcess managedProcess)    at Deadline.Plugins.DeadlinePlugin.StartMonitoredManagedProcessAsUser(String name, ManagedProcess managedProcess, String userName, String domain, String password, Boolean useSu, Boolean preserveEnvironment, Boolean setHomeVariable)    at Deadline.Plugins.DeadlinePlugin.StartMonitoredManagedProcess(String name, ManagedProcess managedProcess) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE05-_I05plugins6093ee9580628310c00de09fNuke.py, line 209, in StartJob     self.StartMonitoredManagedProcess( self.ProcessName, self.Process )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.StartJob()    at Deadline.Plugins.DeadlinePlugin.DoStartJob()    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
73,error error parentinput is not number at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,<> is not a number,,,FALSE,,"Error: FailRenderException : >>> [10:57.57] ERROR: X_Distort1.AdjBBox1.disable: parent.input0 is not a number    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06plugins609cf81c31591321dc7ca7abNuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06plugins609cf81c31591321dc7ca7abNuke.py, line 39, in WritePython     self.WaitForProcess()   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06plugins609cf81c31591321dc7ca7abNuke.py, line 42, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE06plugins609cf81c31591321dc7ca7abNuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
74,error error read read error permission denied at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,read error: permission denied,,,FALSE,,"Error: FailRenderException : >>> [10:47.47] ERROR: Read1: D:/Dropbox/JAM/TJ/TJ00_FX/NJ07_DUST/Boosters/JEFFERSON_BURNERS_0040.png: Read error: Permission denied    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012-_I02plugins609cf5bbd8563c85ac20b322Nuke.py, line 262, in RenderTasks     self.WritePython(scriptContents)   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012-_I02plugins609cf5bbd8563c85ac20b322Nuke.py, line 39, in WritePython     self.WaitForProcess()   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012-_I02plugins609cf5bbd8563c85ac20b322Nuke.py, line 46, in WaitForProcess     self.FlushMonitoredManagedProcessStdout( self.ProcessName )   File C:Userssir.renderAppDataLocalThinkboxDeadline10slaveCOMP012-_I02plugins609cf5bbd8563c85ac20b322Nuke.py, line 621, in HandleError     self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0Dispatcher.Invoke()    at Deadline.Plugins.DeadlinePlugin.RenderTasks()    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
75,error renderer returned nonzero error code check the log for more information at task string outmessage abortlevel,renderer returned non-zero error code,,,FALSE,,"Error: Renderer returned non-zero error code, -536870911. Check the log for more information.    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Redshift
76,the worker did not complete the task before the regular task timeout limit of d h m s the task timeout settings can be changed for this job by rightclicking on it in the monitor and selecting modify properties,the worker did not complete the task before the regular task timeout limit,,,FALSE,,The Worker did not complete the task before the Regular Task Timeout limit of 00d 01h 30m 00s. The Task Timeout settings can be changed for this job by right-clicking on it in the Monitor and selecting Modify Properties....,,,,,,,,,,,,,,,,Redshift
77,event error onjobreleased,event error api authorisation,,,FALSE,,Event Error (OnJobReleased): ApiAuthorisationError : ,,,,,,,,,,,,,,,,Redshift
78,error redshift render executable could not be found in the semicolon separated list the path to the render executable can be configured from the plugin configuration in the deadline monitor at message file line in selffailrender redshift render executable could not be found in the semicolon separated list the path to the render executable can be configured from the plugin configuration in the deadline monitor version at args at version cultureneutral at waitforexit at task string outmessage abortlevel,redshift renderer <> executable could not be found in the semicolon separated list,,,FALSE,,"Error: FailRenderException : Redshift render (1) executable could not be found in the semicolon separated list C:/ProgramData/Redshift/bin/redshiftCmdLine.exe;/usr/redshift/bin/redshiftCmdLine. The path to the render executable can be configured from the Plugin Configuration in the Deadline Monitor.    at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)   File C:UsersAdministratorAppDataLocalThinkboxDeadline10slaveNUKENODE08-_SIMplugins60251761cb0059174cfd50a1Redshift.py, line 56, in RenderExecutable     self.FailRender( Redshift render (%s) executable could not be found in the semicolon separated list %s. The path to the render executable can be configured from the Plugin Configuration in the Deadline Monitor. % ( version, redshiftExeList ) )    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)    at __FranticX_GenericDelegate0`1[[System_String, System_Private_CoreLib, Version=4_0_0_0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]Dispatcher.Invoke()    at FranticX.Processes.ManagedProcess.RenderExecutable()    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Redshift
79,error starting in insufficient system resources exist to complete the requested service at bx string by string bz at executable string arguments string at waitforexit at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,insufficient system resources exist to complete the request service,,,FALSE,,"Error starting C:/ProgramData/Redshift/bin/redshiftCmdLine.exe in C:ProgramDataRedshiftbin : Insufficient system resources exist to complete the requested service.  (System.Exception)    at FranticX.Processes.ChildProcess.i(String bx, String by, String bz)    at FranticX.Processes.ChildProcess.Launch(String executable, String arguments, String startupDirectory)    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Redshift
80,event error onjobfinished exception at least one sequence expected for ffmpeg job none found,<> at least one sequence expected for ffmpeg job. none found,,,FALSE,,Event Error (OnJobFinished): Exception : [FFmpegScenedata] at least one sequence expected for ffmpeg job. None found.,,,,,,,,,,,,,,,,Redshift
81,post job script exception srcdir missing file line in main changes outdir outfilename file line in raise missing formatsrcdir at args at name pyobject args at modulename string functionname object args at scriptfilename boolean prejobscript string outmessage abortlevel,post job script <> missing,,,FALSE,,"Post job script //deadline/DeadlineRepository/custom/events/PPscript/jobscripts/postJobCopyToMaster.py: Exception : src_dir missing. (bstorageprojectsNJ04_PRODUCTIONNJ00_RENDERS03.LRRENDERCAM_OLDNJ074530_NJ074530_NJ07_TK04Escape_Pod) (FranticX.Scripting.PythonNetException)   File //deadline/DeadlineRepository/custom/events/PPscript/jobscripts/postJobCopyToMaster.py, line 60, in __main__     changes += copyFramesToMaster(frameslist, out_dir, out_filename)   File //deadline/DeadlineRepository/custom/events/PPscript/jobscripts/postJobCopyToMaster.py, line 85, in copyFramesToMaster     raise Exception(src_dir missing. ({}).format(src_dir))    at Python.Runtime.PyObject.Invoke(PyObject[] args)    at Python.Runtime.PyObject.InvokeMethod(String name, PyObject[] args)    at FranticX.Scripting.PythonNetScriptEngine.CallFunction(String moduleName, String functionName, Object[] args)    at Deadline.Plugins.PluginWrapper.RenderScript(String scriptFilename, Boolean preJobScript, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,NULL
82,stalled worker report,stalled worker report,,,FALSE,,STALLED WORKER REPORT,,,,,,,,,,,,,,,,Redshift
83,event error onjobsubmitted exception no sound found named in footagewavs,event error onjobsubmitted exception no sound found named <>,,,FALSE,,"Event Error (OnJobSubmitted): Exception : [FINALCOMP_addSound] No sound found named 'NJ_S_CG_CORRIDOR_SET_LIGHT_TK06.0000.wav' in: [., ../../04_FOOTAGE/WAVs, ../../09_FOOTAGE/WAVs]",,,,,,,,,,,,,,,,Redshift
84,error starting in the paging file is too small for this operation to complete at bx string by string bz at executable string arguments string at waitforexit at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,the paging file is too small for this operation to complete,,,FALSE,,"Error starting C:/ProgramData/Redshift/bin/redshiftCmdLine.exe in C:ProgramDataRedshiftbin : The paging file is too small for this operation to complete.  (System.Exception)    at FranticX.Processes.ChildProcess.i(String bx, String by, String bz)    at FranticX.Processes.ChildProcess.Launch(String executable, String arguments, String startupDirectory)    at FranticX.Processes.ManagedProcess.Execute(Boolean waitForExit)    at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)    at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Redshift
85,error strict error checking on caught the following error or file line error reading file this error message is unavoidable but not fatal please email with the error message and disable the maya job setting strict error checking at message file line in rendertasks file line in file line in strict error checking on caught the following error or warningn errormessage nif this error message is unavoidable but not fatal please email with the error message and disable the maya job setting strict error checking at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"strict error checking on, caught the following error or warning. error reading file. ",,,FALSE,,"Error: FailRenderException : Strict error checking on, caught the following error or warning.
Warning: file: C:/Users/sir.render/AppData/Local/Temp/tmpC574.tmp line 49: Error reading file. : //bstorage/projects/NJ/03_PREPRODUCTION/NJ00_PROPS/01_CG_PROPS/NJ_P_CG_JEFFERSON_SPACESHIP/04_RIG/JEFFERSON_PROXY_RIG_MST.ma
If this error message is unavoidable but not fatal, please email support@thinkboxsoftware.com with the error message, and disable the Maya job setting Strict Error Checking.
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\6059b6075cc6803a6cf7948e\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\6059b6075cc6803a6cf7948e\MayaBatch.py"", line 1357, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\6059b6075cc6803a6cf7948e\MayaBatch.py"", line 2668, in HandleErrorMessage
self.deadlinePlugin.FailRender( ""Strict error checking on, caught the following error or warning.\n"" + errorMessage + ""\nIf this error message is unavoidable but not fatal, please email support@thinkboxsoftware.com with the error message, and disable the Maya job setting Strict Error Checking."" )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
86,error strict error checking on caught the following error or warning error file line render failed if this error message is unavoidable but not fatal please email with the error message and disable the maya job setting strict error checking at message file line in rendertasks file line in file line in strict error checking on caught the following error or warningn errormessage nif this error message is unavoidable but not fatal please email with the error message and disable the maya job setting strict error checking at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"strict error checking on, caught the following error or warning. render failed",,,FALSE,,"Error: FailRenderException : Strict error checking on, caught the following error or warning.
Error: file: C:/Users/Administrator/AppData/Local/Temp/tmp4E83.tmp line 69: Render failed.
If this error message is unavoidable but not fatal, please email support@thinkboxsoftware.com with the error message, and disable the Maya job setting Strict Error Checking.
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE02\plugins\605a090893d30a3b34fe5ba3\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE02\plugins\605a090893d30a3b34fe5ba3\MayaBatch.py"", line 1361, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE02\plugins\605a090893d30a3b34fe5ba3\MayaBatch.py"", line 2668, in HandleErrorMessage
self.deadlinePlugin.FailRender( ""Strict error checking on, caught the following error or warning.\n"" + errorMessage + ""\nIf this error message is unavoidable but not fatal, please email support@thinkboxsoftware.com with the error message, and disable the Maya job setting Strict Error Checking."" )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
87,error file line cannot load scene please check the scene path then try opening the scene on the machine which ran this job to troubleshoot the problem at message file line in rendertasks file line in file line in errormessage at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"please check the scene path, then try opening the scene on the machine which ran this job to troubleshoot the problem",,,FALSE,,"Error: FailRenderException : Error: file: C:/Users/sir.render/AppData/Local/Temp/tmpEC90.tmp line 67: Cannot load scene ""//bstorage/projects/CL/03.PRODUCTION/11_CG/0060_CL_LR/0060_CL_LR_TK03.ma"". Please check the scene path, then try opening the scene on the machine which ran this job to troubleshoot the problem.
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\60536baaf557633d648c97e3\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\60536baaf557633d648c97e3\MayaBatch.py"", line 1361, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\60536baaf557633d648c97e3\MayaBatch.py"", line 2658, in HandleErrorMessage
self.deadlinePlugin.FailRender( errorMessage )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
88,error monitored managed process mayabatch has exited or been terminated at name at name at name file line in rendertasks file line in at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,monitored managed process mayabatch has exited or been terminated,,,FALSE,,"Error: ManagedProcessAbort : Monitored managed process ""MayaBatch"" has exited or been terminated.
at Deadline.Plugins.DeadlinePlugin.MonitoredManagedProcessExit(String name)
at FranticX.Processes.MonitoredManagedProcesses.VerifyMonitoredManagedProcess(String name)
at Deadline.Plugins.DeadlinePlugin.VerifyMonitoredManagedProcess(String name) (Python.Runtime.PythonException)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE02\plugins\6054e657f038053cd07a215e\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE02\plugins\6054e657f038053cd07a215e\MayaBatch.py"", line 1360, in WaitForProcess
self.VerifyMonitoredManagedProcess( self.ProcessName )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
89,event error onjoberror the network path was not found,the network path was not found,,,FALSE,,Event Error (OnJobError): The network path was not found. : '\\deadline\DeadlineRepository\events',,,,,,,,,,,,,,,,MayaBatch
90,error maya render executable was not found in the semicolon separated list cprogram the path to the render executable can be configured from the plugin configuration in the deadline monitor at message file line in startjob mayaexecutable file line in maya versionstring render executable was not found in the semicolon separated list mayaexelist the path to the render executable can be configured from the plugin configuration in the deadline monitor at args at outmessage abortlevel abortlevel at outmessage abortlevel,maya render executable was not found in the semicolon separated list,,,FALSE,,"Error: FailRenderException : Maya 2018_0 render executable was not found in the semicolon separated list ""C:\Program Files\Autodesk\Maya2018\bin\MayaBatch.exe;/usr/autodesk/maya2018/bin/maya;/Applications/Autodesk/maya2018/Maya.app/Contents/bin/maya;/usr/autodesk/mayaIO2018/bin/maya"". The path to the render executable can be configured from the Plugin Configuration in the Deadline Monitor.
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA12\plugins\602bb73105a6153020ec7e77\MayaBatch.py"", line 338, in StartJob
mayaExecutable = self.Process.RenderExecutable()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA12\plugins\602bb73105a6153020ec7e77\MayaBatch.py"", line 2558, in RenderExecutable
self.deadlinePlugin.FailRender( ""Maya "" + versionString + "" render executable was not found in the semicolon separated list \"""" + mayaExeList + ""\"". The path to the render executable can be configured from the Plugin Configuration in the Deadline Monitor."" )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.StartJob()
at Deadline.Plugins.DeadlinePlugin.DoStartJob()
at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
91,error dialog popup detected title error message unable to locate valid mayaappdir please specify writable directory where maya can store user data at message file line in rendertasks file line in selffailrender at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unable to locate valid <>. please specify a writable directory where Maya can store user data,,,FALSE,,"Error: FailRenderException : Dialog popup detected: Title ""Error"", Message ""Unable to locate valid MAYA_APP_DIR. Please specify a writable directory where Maya can store user data.""
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\6021581dd10d910e0892f427\MayaBatch.py"", line 421, in RenderTasks
self.WaitForProcess()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\RYZEN01-_I05\plugins\6021581dd10d910e0892f427\MayaBatch.py"", line 1365, in WaitForProcess
self.FailRender( blockingDialogMessage )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
92,error strict error checking on caught the following error or file line could not open file this error message is unavoidable but not fatal please email with the error message and disable the maya job setting strict error checking at message file line in rendertasks file line in file line in strict error checking on caught the following error or warningn errormessage nif this error message is unavoidable but not fatal please email with the error message and disable the maya job setting strict error checking at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,"strict error checking on, caught the following error or warning. could not open file.",,,FALSE,,"Error: FailRenderException : Strict error checking on, caught the following error or warning.
Warning: file: C:/Users/sir.render/AppData/Local/Temp/tmp51EF.tmp line 49: Could not open file. : F:/SIMON/Dropbox/JP_mayaCams/JP_dollyCamRig.ma
If this error message is unavoidable but not fatal, please email support@thinkboxsoftware.com with the error message, and disable the Maya job setting Strict Error Checking.
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA12-_I02\plugins\606f18a5a5893352447a79ad\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA12-_I02\plugins\606f18a5a5893352447a79ad\MayaBatch.py"", line 1361, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA12-_I02\plugins\606f18a5a5893352447a79ad\MayaBatch.py"", line 2668, in HandleErrorMessage
self.deadlinePlugin.FailRender( ""Strict error checking on, caught the following error or warning.\n"" + errorMessage + ""\nIf this error message is unavoidable but not fatal, please email support@thinkboxsoftware.com with the error message, and disable the Maya job setting Strict Error Checking."" )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
93,error rendering was internally aborted at message file line in rendertasks file line in file line in at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,rendering was internally aborted,,,FALSE,,"Error: FailRenderException : Rendering was internally aborted
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE01\plugins\60756231de568832803ab962\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE01\plugins\60756231de568832803ab962\MayaBatch.py"", line 1361, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\GPUNODE01\plugins\60756231de568832803ab962\MayaBatch.py"", line 2596, in HandleFatalError
self.deadlinePlugin.FailRender( self.GetRegexMatch(0) )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
94,error redshift failed to init cuda at message file line in rendertasks file line in file line in at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,failed to init cuda,,,FALSE,,"Error: FailRenderException : [Redshift] Failed to init CUDA (CUDA_ERROR_UNKNOWN)
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA22\plugins\60896d002b04ba1c902e01cd\MayaBatch.py"", line 1200, in RenderTasks
self.WaitForProcess()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA22\plugins\60896d002b04ba1c902e01cd\MayaBatch.py"", line 1361, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA22\plugins\60896d002b04ba1c902e01cd\MayaBatch.py"", line 2596, in HandleFatalError
self.deadlinePlugin.FailRender( self.GetRegexMatch(0) )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,MayaBatch
95,error error unexpected in nanind at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,unexpected <> in <>,,,FALSE,,"Error: FailRenderException : >>> [11:10.17] ERROR: Camera1.translate: unexpected '(' in ""-nan(ind)""
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE01\plugins\607ffa0a33437a4eb4b7270e\Nuke.py"", line 262, in RenderTasks
self.WritePython(scriptContents)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE01\plugins\607ffa0a33437a4eb4b7270e\Nuke.py"", line 39, in WritePython
self.WaitForProcess()
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE01\plugins\607ffa0a33437a4eb4b7270e\Nuke.py"", line 46, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE01\plugins\607ffa0a33437a4eb4b7270e\Nuke.py"", line 621, in HandleError
self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
96,memoryerror,memoryerror,,,FALSE,,MemoryError :,,,,,,,,,,,,,,,,Nuke
97,error error read psd layer compression type is not supported at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,psd layer compression type 8292 is not supported,,,FALSE,,"Error: FailRenderException : >>> [10:04.10] ERROR: Read1: //bstorage/projects/NJ/04_PRODUCTION/NJ02_GREEN_EYED_NOVA/10_COMPOSITING/0530_NJ02_COMP/PSD BG/NJ_S_PS_INT_FANMAIL_STOREROOM.psd: psd layer compression type 8292 is not supported
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA17-_I08\plugins\6058cc0fcada8c0c58e6f6b0\Nuke.py"", line 262, in RenderTasks
self.WritePython(scriptContents)
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA17-_I08\plugins\6058cc0fcada8c0c58e6f6b0\Nuke.py"", line 39, in WritePython
self.WaitForProcess()
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA17-_I08\plugins\6058cc0fcada8c0c58e6f6b0\Nuke.py"", line 46, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\sir.render\AppData\Local\Thinkbox\Deadline10\slave\CONA17-_I08\plugins\6058cc0fcada8c0c58e6f6b0\Nuke.py"", line 621, in HandleError
self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
98,event error onjoberror the event sandbox has not been initialized yet the sandbox must be initialized before sending commands,the event sandbox has not been initialized yet the sandbox must be initialized before sending commands,,,FALSE,,Event Error (OnJobError): The Event Sandbox has not been initialized yet. The Sandbox must be initialized before sending commands.,,,,,,,,,,,,,,,,Nuke
99,interfaceerror connection already closed,interfaceerror connection already closed,,,FALSE,,Event Error (OnJobError): InterfaceError : connection already closed,,,,,,,,,,,,,,,,Nuke
100,value cannot be null parameter key,value cannot be null parameter key,,,FALSE,,Value cannot be null. (Parameter 'key'),,,,,,,,,,,,,,,,Nuke
101,error error read invalid argument at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,error invalid argument,,,FALSE,,"Error: FailRenderException : >>> [10:31.50] ERROR: Read3: Invalid argument
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE03-_I02\plugins\60489fda4494f83b40dc1e9f\Nuke.py"", line 262, in RenderTasks
self.WritePython(scriptContents)
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE03-_I02\plugins\60489fda4494f83b40dc1e9f\Nuke.py"", line 39, in WritePython
self.WaitForProcess()
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE03-_I02\plugins\60489fda4494f83b40dc1e9f\Nuke.py"", line 46, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\Administrator\AppData\Local\Thinkbox\Deadline10\slave\NUKENODE03-_I02\plugins\60489fda4494f83b40dc1e9f\Nuke.py"", line 621, in HandleError
self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
at __FranticX_GenericDelegate0Dispatcher.Invoke()
at Deadline.Plugins.DeadlinePlugin.RenderTasks()
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks()
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
102,event error onjobsubmitted exception scenefile is blank,error: scenefile is blank,,,FALSE,,Event Error (OnJobSubmitted): Exception : SceneFile is blank,,,,,,,,,,,,,,,,Nuke
103,error windowserror error cannot create file when that file already exists at message file line in rendertasks file line in writepython file line in file line in handleerror at args at task string outmessage abortlevel abortlevel at task string outmessage abortlevel,cannot create a file when that file already exists,,,FALSE,,"Error: FailRenderException : WindowsError: [Error 183] Cannot create a file when that file already exists: '//bstorage/projects/NJ/04_PRODUCTION/NJ00_RENDERS/01.COMP/NJ03/2310_NJ03/exr'
at Deadline.Plugins.DeadlinePlugin.FailRender(String message) (Python.Runtime.PythonException) 
File ""C:\Users\jon.tennent\AppData\Local\Thinkbox\Deadline10\slave\CONA03-_I06\plugins\607562ab645c05662ca36e60\Nuke.py"", line 262, in RenderTasks
self.WritePython(scriptContents)
File ""C:\Users\jon.tennent\AppData\Local\Thinkbox\Deadline10\slave\CONA03-_I06\plugins\607562ab645c05662ca36e60\Nuke.py"", line 39, in WritePython
self.WaitForProcess()
File ""C:\Users\jon.tennent\AppData\Local\Thinkbox\Deadline10\slave\CONA03-_I06\plugins\607562ab645c05662ca36e60\Nuke.py"", line 42, in WaitForProcess
self.FlushMonitoredManagedProcessStdout( self.ProcessName )
File ""C:\Users\jon.tennent\AppData\Local\Thinkbox\Deadline10\slave\CONA03-_I06\plugins\607562ab645c05662ca36e60\Nuke.py"", line 621, in HandleError
self.deadlinePlugin.FailRender( self.GetRegexMatch( 0 ) )
at Python.Runtime.Dispatcher.Dispatch(ArrayList args) 
at __FranticX_GenericDelegate0Dispatcher.Invoke() 
at Deadline.Plugins.DeadlinePlugin.RenderTasks() 
at Deadline.Plugins.DeadlinePlugin.DoRenderTasks() 
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel) 
at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)",,,,,,,,,,,,,,,,Nuke
